version: '3.8'
services:
  app:
    build: .
    container_name: myapp-go
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=username
      - DB_PASS=password
      - DB_NAME=db
    depends_on:
      postgres:
          condition: service_healthy
  postgres:
    image: postgres:13
    container_name: myapp-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
